"""
FastAPI backend for AjanDB: upload unstructured files -> markdown in SQLite,
keyword search over stored files, and a chatbot endpoint that compiles a
book from whatever matches a topic.

Run with:
    uvicorn backend.main:app --reload --app-dir webapp
"""
import mimetypes
import os
import re
import shutil
import tempfile
import threading
import uuid
from urllib.parse import quote

import requests
from fastapi import FastAPI, File, Form, HTTPException, Request, Response, UploadFile
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from . import book_compiler, categorize, content_studio, convert, db, originals, review, sources, tts

app = FastAPI(title="AjanDB")

_FRONTEND_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend"
)


@app.get("/images/{filename}")
def get_image(filename: str):
    """Serves an extracted image (see convert.py's _save_image_as_jpg) -
    a plain route reading convert.IMAGES_DIR fresh on every request rather
    than a StaticFiles mount, which would otherwise bake in whatever
    directory existed at import time and not follow along if that ever
    changes (as it does in tests, via monkeypatch). filename is reduced to
    its basename first so a malformed value can't escape IMAGES_DIR."""
    path = os.path.join(convert.IMAGES_DIR, os.path.basename(filename))
    if not os.path.isfile(path):
        raise HTTPException(404, "Image not found")
    return FileResponse(path, media_type="image/jpeg")


@app.get("/audio/{filename}")
def get_audio(filename: str):
    """Serves generated speech audio (see tts.py) - same pattern as
    get_image above: a plain route reading tts.AUDIO_DIR fresh on every
    request, not a StaticFiles mount, so tests can monkeypatch it."""
    path = os.path.join(tts.AUDIO_DIR, os.path.basename(filename))
    if not os.path.isfile(path):
        raise HTTPException(404, "Audio not found")
    return FileResponse(path, media_type="audio/mpeg")


@app.get("/generated-images/{filename}")
def get_generated_image(filename: str):
    """Serves an image generated by content_studio.py - same pattern as
    get_image/get_audio above."""
    path = os.path.join(content_studio.IMAGES_DIR, os.path.basename(filename))
    if not os.path.isfile(path):
        raise HTTPException(404, "Image not found")
    return FileResponse(path, media_type="image/png")


@app.get("/generated-videos/{filename}")
def get_generated_video(filename: str):
    """Serves a video assembled by content_studio.py - same pattern as
    get_image/get_audio above."""
    path = os.path.join(content_studio.VIDEOS_DIR, os.path.basename(filename))
    if not os.path.isfile(path):
        raise HTTPException(404, "Video not found")
    return FileResponse(path, media_type="video/mp4")


def _resolve_client_key(provider: str | None, anthropic_key: str | None,
                         openai_key: str | None) -> str | None:
    """Picks whichever browser-supplied key matches `provider` (defaulting
    to "anthropic", same default every provider-aware module here uses).
    Returns None when the matching key wasn't supplied - callers then fall
    back to the backend's own environment variables, unchanged."""
    resolved_provider = (provider or "anthropic").lower()
    return openai_key if resolved_provider == "openai" else anthropic_key


# --- Upload jobs ---
#
# OCR (classical or vision-LLM) can take anywhere from milliseconds to many
# minutes per document, and this app is typically reached through a tunnel
# (cloudflared, ngrok, ...) or a flaky mobile connection - neither promises
# a single HTTP request stays alive that long. A request that does get cut
# mid-flight shows up client-side as "<!DOCTYPE ...> is not valid JSON" (the
# tunnel/proxy's own error page instead of our JSON), which is exactly what
# happened here: real conversion work was still running when the connection
# was cancelled after several minutes.
#
# So /api/upload does no OCR itself: it saves the file, hands the actual
# work to a background thread, and returns a job id immediately. The
# frontend polls /api/upload/{job_id} - each poll is a fast, cheap request,
# so nothing depends on one connection surviving the whole conversion.
# In-memory (not persisted) is fine here: single-process app, jobs are
# short-lived, and a restart mid-job would have lost that upload anyway.
_jobs: dict[str, dict] = {}
_jobs_lock = threading.Lock()

# Log lines per job, kept separate from `_jobs` (which _set_job overwrites
# wholesale on every status change) so the running "converting / saved"
# history survives from "processing" through to "done"/"error" - the
# frontend polls this alongside status to render a live console instead of
# just a single current-status line.
_job_logs: dict[str, list[str]] = {}


def _set_job(job_id: str, **fields):
    with _jobs_lock:
        _jobs[job_id] = fields


def _upload_log(job_id: str, message: str):
    print(f"[upload {job_id[:8]}] {message}", flush=True)
    with _jobs_lock:
        _job_logs.setdefault(job_id, []).append(message)


def _run_upload_job(job_id: str, tmp_path: str, filename: str, ext: str,
                     engine: str, provider: str | None, model: str | None,
                     category: str | None, anthropic_api_key: str | None,
                     openai_api_key: str | None):
    vision_key = _resolve_client_key(provider, anthropic_api_key, openai_api_key)
    _upload_log(job_id, f"Starting: {filename} (engine={engine}, provider={provider or 'default'})")

    def _progress(page_number: int, total_pages: int):
        _upload_log(job_id, f"Converting page {page_number + 1}/{total_pages}...")

    try:
        chunks = convert.convert_to_markdown(
            tmp_path, filename, engine=engine, provider=provider, model=model,
            api_key=vision_key, progress=_progress)
        originals.save(tmp_path, filename, len(chunks))
    except ValueError as e:
        _upload_log(job_id, f"ERROR: {e}")
        _set_job(job_id, status="error", code=400, detail=str(e))
        return
    except RuntimeError as e:
        _upload_log(job_id, f"ERROR: {e}")
        _set_job(job_id, status="error", code=503, detail=str(e))
        return
    except Exception as e:
        _upload_log(job_id, f"ERROR: Failed to convert {filename}: {e}")
        _set_job(job_id, status="error", code=422, detail=f"Failed to convert {filename}: {e}")
        return
    finally:
        os.unlink(tmp_path)

    _upload_log(job_id, f"Converted {filename}: {len(chunks)} chunk(s)")

    resolved_category = (category or "").strip()
    if not resolved_category:
        sample_text = "\n\n".join(c["markdown"] for c in chunks[:2])
        if anthropic_api_key:
            resolved_category = categorize.suggest_category(
                sample_text, provider="anthropic", api_key=anthropic_api_key) or "Uncategorized"
        elif openai_api_key:
            resolved_category = categorize.suggest_category(
                sample_text, provider="openai", api_key=openai_api_key) or "Uncategorized"
        else:
            resolved_category = categorize.suggest_category(
                sample_text, provider=provider, model=model) or "Uncategorized"

    source_type = ext.lstrip(".")
    conn = db.get_connection()  # own connection - sqlite3 connections aren't shared across threads
    try:
        chunk_ids = db.insert_chunks(conn, filename, source_type, resolved_category, chunks)
    finally:
        conn.close()

    _upload_log(job_id, f"Done: saved {len(chunk_ids)} chunk(s), category '{resolved_category}'")
    _set_job(
        job_id, status="done",
        result={
            "source_filename": filename,
            "source_type": source_type,
            "category": resolved_category,
            "chunks": [{"id": cid, **chunk} for cid, chunk in zip(chunk_ids, chunks)],
        },
    )


@app.post("/api/upload")
async def upload(
    file: UploadFile = File(...),
    engine: str = Form("classical"),
    provider: str | None = Form(None),
    model: str | None = Form(None),
    category: str | None = Form(None),
    anthropic_api_key: str | None = Form(None),
    openai_api_key: str | None = Form(None),
):
    """`engine`="vision" routes scanned PDF pages through a per-page LLM call
    (`provider`: "anthropic" or "openai") instead of local Tesseract - see
    convert.pdf_to_markdown_vision. Needs the matching API key, either typed
    into the frontend (sent here as `anthropic_api_key`/`openai_api_key` -
    stored only in the browser, never persisted server-side) or set as
    ANTHROPIC_API_KEY/OPENAI_API_KEY in the backend's environment; neither
    is the same as a claude.ai/ChatGPT Plus subscription.

    `category` is optional - leave it blank to have it auto-suggested from
    the converted content using whichever key is available (falls back to
    "Uncategorized" if none is; that's never a hard failure).

    Returns immediately with a job id - the actual conversion (which can
    take a long time for scanned PDFs) runs in the background. Poll
    GET /api/upload/{job_id} for the result."""
    ext = os.path.splitext(file.filename or "")[1].lower()
    if ext not in convert.SUPPORTED_EXTENSIONS:
        raise HTTPException(400, f"Unsupported file type: {ext or '(none)'}")

    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name

    job_id = uuid.uuid4().hex
    _set_job(job_id, status="processing")
    threading.Thread(
        target=_run_upload_job,
        args=(job_id, tmp_path, file.filename, ext, engine, provider, model,
              category, anthropic_api_key, openai_api_key),
        daemon=True,
    ).start()

    return {"job_id": job_id, "status": "processing"}


def _job_status_response(job_id: str, not_found_detail: str) -> dict:
    """Shared polling response shape for every background-job endpoint
    (uploads, and content-generation below) - each job is just a job_id
    key into the same `_jobs`/`_job_logs` dicts regardless of what kind of
    work it's tracking."""
    with _jobs_lock:
        job = _jobs.get(job_id)
        log = list(_job_logs.get(job_id, []))
    if not job:
        raise HTTPException(404, not_found_detail)
    if job["status"] == "processing":
        return {"status": "processing", "log": log}
    if job["status"] == "error":
        raise HTTPException(job["code"], job["detail"])
    return {"status": "done", "log": log, **job["result"]}


@app.get("/api/upload/{job_id}")
def upload_status(job_id: str):
    return _job_status_response(job_id, "Unknown upload job")


class ReviewApproveRequest(BaseModel):
    markdown: str | None = None  # a human edit to save instead of the converted text, if given
    needs_review: bool | None = None  # override the auto-computed flag, if given


@app.post("/api/review/start")
async def review_start(
    file: UploadFile = File(...),
    engine: str = Form("classical"),
    provider: str | None = Form(None),
    model: str | None = Form(None),
    langs: str | None = Form(None),
    category: str | None = Form(None),
    anthropic_api_key: str | None = Form(None),
    openai_api_key: str | None = Form(None),
    auto_validate: bool = Form(False),
):
    """Starts a page-by-page review session: converts and returns page 1
    immediately, alongside a rendered preview image, so the frontend can
    show scan-vs-markdown side by side and let a human approve (optionally
    after editing) or skip each page before it's saved - see
    backend/review.py for the full flow. PDF only; other file types have no
    OCR step for a human to check page-by-page."""
    ext = os.path.splitext(file.filename or "")[1].lower()
    if ext != ".pdf":
        raise HTTPException(400, "Page-by-page review is only supported for PDFs")
    if engine not in ("classical", "vision"):
        raise HTTPException(400, f"Unknown conversion engine {engine!r} - expected 'classical' or 'vision'")

    api_key = _resolve_client_key(provider, anthropic_api_key, openai_api_key)

    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
        shutil.copyfileobj(file.file, tmp)
        tmp_path = tmp.name

    try:
        return review.start(
            tmp_path, file.filename, engine=engine, provider=provider, model=model,
            langs=langs, category=category, api_key=api_key, auto_validate=auto_validate)
    except ValueError as e:
        os.unlink(tmp_path)
        raise HTTPException(400, str(e))
    except RuntimeError as e:
        os.unlink(tmp_path)
        raise HTTPException(503, str(e))
    except Exception as e:
        os.unlink(tmp_path)
        raise HTTPException(422, f"Failed to convert page 1 of {file.filename}: {e}")


@app.post("/api/review/{session_id}/approve")
def review_approve(session_id: str, req: ReviewApproveRequest):
    try:
        return review.approve(session_id, markdown=req.markdown, needs_review=req.needs_review)
    except KeyError:
        raise HTTPException(404, "Unknown review session")
    except RuntimeError as e:
        raise HTTPException(503, str(e))
    except Exception as e:
        raise HTTPException(422, f"Failed to convert the next page: {e}")


@app.post("/api/review/{session_id}/skip")
def review_skip(session_id: str):
    try:
        return review.skip(session_id)
    except KeyError:
        raise HTTPException(404, "Unknown review session")
    except RuntimeError as e:
        raise HTTPException(503, str(e))
    except Exception as e:
        raise HTTPException(422, f"Failed to convert the next page: {e}")


@app.post("/api/review/{session_id}/retry")
def review_retry(session_id: str):
    """Re-attempts converting the page after the last approve()/skip() call -
    use this if that request failed (e.g. a transient vision-LLM API error)
    instead of resubmitting approve()/skip(), which would reject the retry
    as there being nothing currently pending."""
    try:
        return review.retry(session_id)
    except KeyError:
        raise HTTPException(404, "Unknown review session")
    except RuntimeError as e:
        raise HTTPException(503, str(e))
    except Exception as e:
        raise HTTPException(422, f"Failed to convert the next page: {e}")


class VerifyRequest(BaseModel):
    provider: str | None = None  # which vision-LLM to cross-check against - "anthropic" (default) or "openai"
    model: str | None = None
    anthropic_api_key: str | None = None  # typed into the frontend - stored only in the browser
    openai_api_key: str | None = None


@app.post("/api/review/{session_id}/verify")
def review_verify(session_id: str, req: VerifyRequest):
    """Cross-checks the page currently awaiting review against a second
    vision-LLM call, independent of whatever engine/provider produced the
    pending transcription, and returns a word-level diff plus an agreement
    percentage - see review.verify_second_opinion for why this is a more
    trustworthy signal than either model's own confidence score. Doesn't
    touch approve/skip/save state; safe to call more than once."""
    api_key = _resolve_client_key(req.provider, req.anthropic_api_key, req.openai_api_key)
    try:
        return review.verify_second_opinion(
            session_id, provider=req.provider, model=req.model, api_key=api_key)
    except KeyError:
        raise HTTPException(404, "Unknown review session")
    except RuntimeError as e:
        raise HTTPException(503, str(e))
    except Exception as e:
        raise HTTPException(422, f"Failed to get a second opinion: {e}")


@app.post("/api/review/{session_id}/cancel")
def review_cancel(session_id: str):
    try:
        return review.cancel(session_id)
    except KeyError:
        raise HTTPException(404, "Unknown review session")


class TTSRequest(BaseModel):
    text: str
    azure_speech_key: str | None = None  # typed into the frontend - stored only in the browser
    azure_speech_region: str | None = None


@app.post("/api/tts")
def synthesize_speech(req: TTSRequest):
    """Generates (or reuses a cached) speech audio file for `req.text` via
    Azure Speech - see tts.py. Returns {"audio_url": "/audio/<hash>.mp3"}."""
    if not req.text.strip():
        raise HTTPException(400, "text is required")
    try:
        audio_url = tts.get_or_synthesize(
            req.text, region=req.azure_speech_region, api_key=req.azure_speech_key)
    except RuntimeError as e:
        raise HTTPException(503, str(e))
    except requests.HTTPError as e:
        raise HTTPException(502, f"TTS provider error: {e}")
    return {"audio_url": audio_url}


@app.get("/api/documents")
def list_documents():
    conn = db.get_connection()
    try:
        return db.list_documents(conn)
    finally:
        conn.close()


@app.get("/api/documents/{doc_id}")
def get_document(doc_id: int):
    conn = db.get_connection()
    try:
        doc = db.get_document(conn, doc_id)
    finally:
        conn.close()
    if not doc:
        raise HTTPException(404, "Document not found")
    return doc


@app.get("/api/books")
def list_books():
    """One entry per uploaded source file (whether it needed OCR or was
    stored as-is), for browsing the library rather than searching it - see
    db.list_books()'s docstring for how "one book" is identified. Each
    entry is annotated with `resumable` - whether a page-by-page review of
    this exact book was cancelled or abandoned partway through and can be
    continued (see sources.py) - and `has_original` - whether the original
    uploaded file was retained and can be viewed/exported (see
    originals.py; false for books ingested via scripts/chunked_upload.py,
    which never goes through this app's upload endpoints) - on top of
    whatever db.list_books() itself returns (pages_stored/total_pages,
    ready_for_publish, ...)."""
    conn = db.get_connection()
    try:
        books = db.list_books(conn)
    finally:
        conn.close()
    for book in books:
        book["resumable"] = sources.exists(book["source_filename"], book["total_pages"])
        book["has_original"] = originals.exists(book["source_filename"], book["total_pages"])
    return books


@app.get("/api/books/{book_id}")
def get_book(book_id: int):
    conn = db.get_connection()
    try:
        chunks = db.get_book_chunks(conn, book_id)
    finally:
        conn.close()
    if not chunks:
        raise HTTPException(404, "Book not found")
    first = chunks[0]
    return {
        "source_filename": first["source_filename"],
        "source_type": first["source_type"],
        "total_pages": first["total_pages"],
        "category": first["category"],
        "chunks": chunks,
    }


@app.delete("/api/books/{book_id}")
def delete_book(book_id: int):
    """Deletes every stored page of this book - see db.delete_book()'s
    docstring for exactly what is and isn't touched there (images are left
    alone, since one can be shared by content hash with another book). Any
    resumable source (sources.py) and retained original file (originals.py)
    for this exact book are also cleaned up here, since there's nothing
    left to resume or export once the book itself is gone."""
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
        deleted = db.delete_book(conn, book_id)
    finally:
        conn.close()
    if not deleted:
        raise HTTPException(404, "Book not found")
    if identity:
        sources.delete(identity[0], identity[1])
        originals.delete(identity[0], identity[1])
    return {"deleted_pages": deleted}


class ReadyForPublishRequest(BaseModel):
    ready: bool = True


@app.post("/api/books/{book_id}/ready-for-publish")
def set_book_ready_for_publish(book_id: int, req: ReadyForPublishRequest):
    """Marks (or unmarks) a book as ready for publish - a manual, purely
    organisational flag for the person curating this library; nothing here
    actually publishes anything."""
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
        if not identity:
            raise HTTPException(404, "Book not found")
        db.set_ready_for_publish(conn, identity[0], identity[1], req.ready)
    finally:
        conn.close()
    return {"ready_for_publish": req.ready}


class SetBookLabelRequest(BaseModel):
    key: str
    value: str


@app.put("/api/books/{book_id}/labels")
def set_book_label(book_id: int, req: SetBookLabelRequest):
    """Sets (or overwrites) one free-form key/value label on a book - see
    db.set_book_label()'s docstring for why there's no fixed key list
    enforced here; the frontend suggests common ones (publish date, media
    type, content, author/publisher) plus a custom-key option, but any
    non-empty key is accepted."""
    key = req.key.strip()
    if not key:
        raise HTTPException(400, "Label key cannot be empty")
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
        if not identity:
            raise HTTPException(404, "Book not found")
        db.set_book_label(conn, identity[0], identity[1], key, req.value)
        labels = db.get_book_labels(conn, identity[0], identity[1])
    finally:
        conn.close()
    return {"labels": labels}


@app.delete("/api/books/{book_id}/labels/{key}")
def delete_book_label(book_id: int, key: str):
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
        if not identity:
            raise HTTPException(404, "Book not found")
        db.delete_book_label(conn, identity[0], identity[1], key)
        labels = db.get_book_labels(conn, identity[0], identity[1])
    finally:
        conn.close()
    return {"labels": labels}


class ResumeReviewRequest(BaseModel):
    anthropic_api_key: str | None = None  # typed into the frontend - stored only in the browser
    openai_api_key: str | None = None


@app.post("/api/books/{book_id}/resume")
def resume_book_review(book_id: int, req: ResumeReviewRequest):
    """Continues a page-by-page review that was cancelled or abandoned
    before every page was decided - see review.resume() for exactly what
    "resumable" means and why the original session's own API key can't
    just be reused."""
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
    finally:
        conn.close()
    if not identity:
        raise HTTPException(404, "Book not found")
    source_filename, total_pages = identity

    loaded = sources.load(source_filename, total_pages)
    api_key = None
    if loaded is not None:
        _, settings = loaded
        api_key = _resolve_client_key(settings.get("provider"), req.anthropic_api_key, req.openai_api_key)
    try:
        return review.resume(source_filename, total_pages, api_key=api_key)
    except FileNotFoundError as e:
        raise HTTPException(404, str(e))
    except RuntimeError as e:
        raise HTTPException(503, str(e))


def _book_to_markdown(chunks: list[dict]) -> str:
    first = chunks[0]
    lines = [
        f"# {first['source_filename']}", "",
        f"*Category: {first['category']} · {first['total_pages']} page(s)*", "",
    ]
    for chunk in chunks:
        lines.append(f"## Page {chunk['page_number']}")
        lines.append("")
        lines.append(chunk["markdown"])
        lines.append("")
    return "\n".join(lines)


def _export_filename(source_filename: str) -> str:
    base = os.path.splitext(source_filename)[0]
    return f"{base}.md"


def _content_disposition(filename: str, disposition: str = "attachment") -> str:
    # A non-ASCII filename (very possible here - e.g. a Thai book title)
    # can't go in the plain `filename=` parameter, so it's UTF-8
    # percent-encoded per RFC 5987 in `filename*=`, with an ASCII-only
    # fallback in `filename=` for anything that doesn't support that.
    ascii_fallback = re.sub(r'[^\x20-\x7E]', "_", filename).replace('"', "'") or "export.md"
    return f"{disposition}; filename=\"{ascii_fallback}\"; filename*=UTF-8''{quote(filename)}"


_IMAGE_LINK_RE = re.compile(r"(!\[[^\]]*\]\()(/images/[^)]+)(\))")


def _absolutize_image_links(markdown: str, request: Request) -> str:
    """Stored markdown references images by a host-relative /images/<hash>.jpg
    path (see convert.py), which resolves correctly wherever the app itself
    is being browsed from - but a downloaded .md file has no "current page"
    to resolve a relative link against, so exporting rewrites each one to a
    full URL against whatever host served this request (localhost, a
    cloudflared tunnel, ...). Opening the export elsewhere, or after this
    server has stopped running, will show broken image links - there's no
    way around that without bundling the image files with the export too."""
    base = str(request.base_url).rstrip("/")
    return _IMAGE_LINK_RE.sub(lambda m: f"{m.group(1)}{base}{m.group(2)}{m.group(3)}", markdown)


@app.get("/api/books/{book_id}/export")
def export_book(book_id: int, request: Request):
    """Downloads one book's full chunk set as a single concatenated
    markdown file, in page order - the only way any converted text leaves
    the database as an actual file (it's otherwise stored purely as text
    in SQLite, never written to disk - see the README's "Where is the
    output .md saved?" note)."""
    conn = db.get_connection()
    try:
        chunks = db.get_book_chunks(conn, book_id)
    finally:
        conn.close()
    if not chunks:
        raise HTTPException(404, "Book not found")
    markdown = _absolutize_image_links(_book_to_markdown(chunks), request)
    filename = _export_filename(chunks[0]["source_filename"])
    return Response(
        content=markdown, media_type="text/markdown",
        headers={"Content-Disposition": _content_disposition(filename)},
    )


def _serve_original(book_id: int, disposition: str) -> FileResponse:
    conn = db.get_connection()
    try:
        identity = db.get_book_identity(conn, book_id)
    finally:
        conn.close()
    if identity is None:
        raise HTTPException(404, "Book not found")
    source_filename, total_pages = identity
    path = originals.load(source_filename, total_pages)
    if path is None:
        raise HTTPException(404, "No original file was retained for this book")
    media_type = mimetypes.guess_type(source_filename)[0] or "application/octet-stream"
    return FileResponse(
        path, media_type=media_type,
        headers={"Content-Disposition": _content_disposition(source_filename, disposition)},
    )


@app.get("/api/books/{book_id}/original")
def view_book_original(book_id: int):
    """Streams the original uploaded file for inline viewing (e.g. a PDF
    opened in the browser's own viewer) rather than a forced download -
    see export_book_original for the download variant, and originals.py
    for what is and isn't retained."""
    return _serve_original(book_id, "inline")


@app.get("/api/books/{book_id}/original/export")
def export_book_original(book_id: int):
    """Downloads the exact original file this book was uploaded from, if
    one was retained - see originals.py."""
    return _serve_original(book_id, "attachment")


@app.get("/api/search")
def search(q: str):
    conn = db.get_connection()
    try:
        return db.search(conn, q)
    finally:
        conn.close()


# --- Data Generation ---
#
# Two output modes, picked by `output_mode`:
#   - "copy_paste": pure retrieval, no model call (book_compiler.compile_copy_paste).
#   - "generative": build new material around the matched sources, in one of
#     four mutually-exclusive `generative_mode`s - "text" (default) and
#     "flow" both return markdown (book_compiler.compile_book); "image" and
#     "video" return generated media (content_studio.py). Each replaces the
#     others rather than stacking, since e.g. "video" already produces its
#     own script text internally - there's no separate "text" output to add
#     on top of it.
#
# Runs as a background job, same reasoning and pattern as /api/upload:
# image generation and especially video assembly (LLM call + image-API call
# + TTS call + ffmpeg) can take long enough that a single request risks the
# same tunnel-timeout problem uploads once hit.

def _content_log(job_id: str, message: str):
    print(f"[generate {job_id[:8]}] {message}", flush=True)
    with _jobs_lock:
        _job_logs.setdefault(job_id, []).append(message)


def _run_content_job(job_id: str, instruction: str, output_mode: str, generative_mode: str | None,
                      provider: str | None, model: str | None, anthropic_api_key: str | None,
                      openai_api_key: str | None, azure_speech_key: str | None,
                      azure_speech_region: str | None):
    conn = db.get_connection()
    try:
        if output_mode == "copy_paste":
            _content_log(job_id, "Retrieving matching source material...")
            result = {"kind": "text", **book_compiler.compile_copy_paste(instruction, conn)}
        elif output_mode == "generative":
            mode = generative_mode or "text"
            if mode in ("text", "flow"):
                _content_log(job_id, "Generating content...")
                api_key = _resolve_client_key(provider, anthropic_api_key, openai_api_key)
                result = {"kind": "text", **book_compiler.compile_book(
                    instruction, conn, provider=provider, model=model, api_key=api_key, mode=mode)}
            elif mode == "image":
                _content_log(job_id, "Generating image...")
                image_key = _resolve_client_key("openai", anthropic_api_key, openai_api_key)
                result = {"kind": "image", **content_studio.generate_image(instruction, conn, api_key=image_key)}
            elif mode == "video":
                _content_log(job_id, "Writing narration script...")
                text_key = _resolve_client_key(provider, anthropic_api_key, openai_api_key)
                image_key = _resolve_client_key("openai", anthropic_api_key, openai_api_key)
                result = {"kind": "video", **content_studio.generate_video(
                    instruction, conn, text_provider=provider, text_model=model, text_api_key=text_key,
                    image_api_key=image_key, azure_speech_key=azure_speech_key,
                    azure_speech_region=azure_speech_region)}
            else:
                raise ValueError(f"Unknown generative_mode {mode!r} - expected 'text', 'flow', 'image', or 'video'")
        else:
            raise ValueError(f"Unknown output_mode {output_mode!r} - expected 'copy_paste' or 'generative'")
        _content_log(job_id, "Done.")
        _set_job(job_id, status="done", result=result)
    except ValueError as e:
        _content_log(job_id, f"ERROR: {e}")
        _set_job(job_id, status="error", code=400, detail=str(e))
    except RuntimeError as e:
        _content_log(job_id, f"ERROR: {e}")
        _set_job(job_id, status="error", code=503, detail=str(e))
    except Exception as e:
        _content_log(job_id, f"ERROR: {e}")
        _set_job(job_id, status="error", code=502, detail=f"Content generation failed: {e}")
    finally:
        conn.close()


class ContentGenerateRequest(BaseModel):
    instruction: str
    output_mode: str  # "copy_paste" or "generative"
    generative_mode: str | None = None  # "text" (default), "flow", "image", or "video" - generative only
    provider: str | None = None  # "anthropic" (default) or "openai" - picks the text model
    model: str | None = None
    anthropic_api_key: str | None = None  # typed into the frontend - stored only in the browser
    openai_api_key: str | None = None
    azure_speech_key: str | None = None  # only used by generative_mode "video"
    azure_speech_region: str | None = None


@app.post("/api/generate")
def start_content_generation(req: ContentGenerateRequest):
    job_id = uuid.uuid4().hex
    _set_job(job_id, status="processing")
    threading.Thread(
        target=_run_content_job,
        args=(job_id, req.instruction, req.output_mode, req.generative_mode, req.provider, req.model,
              req.anthropic_api_key, req.openai_api_key, req.azure_speech_key, req.azure_speech_region),
        daemon=True,
    ).start()
    return {"job_id": job_id, "status": "processing"}


@app.get("/api/generate/{job_id}")
def content_generation_status(job_id: str):
    return _job_status_response(job_id, "Unknown content-generation job")


# Serve the frontend last so it doesn't shadow the /api/* routes above.
app.mount("/", StaticFiles(directory=_FRONTEND_DIR, html=True), name="frontend")
