import base64
import subprocess
from types import SimpleNamespace

import pytest

from backend import content_studio, db


def _tmp_conn(tmp_path):
    return db.get_connection(str(tmp_path / "test.sqlite3"))


def _insert(conn, filename, content, category="Uncategorized"):
    chunk = [{"page_number": 1, "markdown": content, "confidence": None, "needs_review": False}]
    db.insert_chunks(conn, filename, "md", category, chunk)


def _tiny_png_bytes() -> bytes:
    """A real, valid 64x64 PNG generated by ffmpeg itself - so decoding and
    handing it to the real ffmpeg assembly step in the video tests below
    actually works, not just a mock returning arbitrary bytes."""
    result = subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=blue:s=64x64",
         "-frames:v", "1", "-update", "1", "-f", "image2pipe", "-vcodec", "png", "pipe:1"],
        capture_output=True,
    )
    assert result.returncode == 0, result.stderr
    return result.stdout


def _tiny_mp3_bytes() -> bytes:
    """A real, valid ~0.3s silent MP3, same reasoning as _tiny_png_bytes."""
    result = subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi", "-i", "anullsrc=r=8000:cl=mono",
         "-t", "0.3", "-q:a", "9", "-f", "mp3", "pipe:1"],
        capture_output=True,
    )
    assert result.returncode == 0, result.stderr
    return result.stdout


class _FakeImageData:
    def __init__(self, b64_json):
        self.b64_json = b64_json


class _FakeImagesAPI:
    def __init__(self, image_bytes):
        self._image_bytes = image_bytes
        self.calls = []

    def generate(self, **kwargs):
        self.calls.append(kwargs)
        return SimpleNamespace(data=[_FakeImageData(base64.b64encode(self._image_bytes).decode())])


class _FakeOpenAIImageClient:
    def __init__(self, image_bytes, api_key=None):
        self.images = _FakeImagesAPI(image_bytes)


# --- generate_image ---

def test_generate_image_raises_without_api_key(tmp_path):
    conn = _tmp_conn(tmp_path)
    with pytest.raises(RuntimeError, match="OpenAI"):
        content_studio.generate_image("a topic", conn, api_key=None)


def test_generate_image_saves_the_returned_bytes_and_returns_a_url(monkeypatch, tmp_path):
    conn = _tmp_conn(tmp_path)
    _insert(conn, "parenting.md", "Tips on how to raise a child with patience.")
    png_bytes = _tiny_png_bytes()
    fake_client = _FakeOpenAIImageClient(png_bytes)
    monkeypatch.setattr(content_studio, "OpenAI", lambda api_key=None: fake_client)

    result = content_studio.generate_image("raising a child", conn, api_key="fake")

    assert result["image_url"].startswith(content_studio.IMAGES_URL_PREFIX + "/")
    assert result["sources"] == ["parenting.md (page 1/1)"]
    assert "raising a child" in result["prompt"]

    import os
    saved_path = os.path.join(content_studio.IMAGES_DIR, os.path.basename(result["image_url"]))
    assert os.path.exists(saved_path)
    with open(saved_path, "rb") as f:
        assert f.read() == png_bytes


def test_generate_image_calls_are_never_deduped(monkeypatch, tmp_path):
    # unlike tts.py/convert.py's content-hash caches, image generation is
    # non-deterministic - two calls for the same instruction must each hit
    # the API and produce a distinct file.
    conn = _tmp_conn(tmp_path)
    fake_client = _FakeOpenAIImageClient(_tiny_png_bytes())
    monkeypatch.setattr(content_studio, "OpenAI", lambda api_key=None: fake_client)

    result1 = content_studio.generate_image("raising a child", conn, api_key="fake")
    result2 = content_studio.generate_image("raising a child", conn, api_key="fake")

    assert result1["image_url"] != result2["image_url"]
    assert len(fake_client.images.calls) == 2


def test_generate_image_prompt_includes_matched_source_labels(monkeypatch, tmp_path):
    conn = _tmp_conn(tmp_path)
    _insert(conn, "parenting.md", "Tips on how to raise a child with patience.")
    fake_client = _FakeOpenAIImageClient(_tiny_png_bytes())
    monkeypatch.setattr(content_studio, "OpenAI", lambda api_key=None: fake_client)

    content_studio.generate_image("raising a child", conn, api_key="fake")

    assert "parenting.md" in fake_client.images.calls[0]["prompt"]


# --- generate_video ---

def test_generate_video_raises_without_azure_key(monkeypatch, tmp_path):
    conn = _tmp_conn(tmp_path)
    _insert(conn, "parenting.md", "Tips on how to raise a child with patience.")
    monkeypatch.setattr(
        content_studio.book_compiler, "compile_book",
        lambda *a, **k: {"markdown": "Some narration.", "sources": ["parenting.md (page 1/1)"]},
    )
    monkeypatch.setattr(content_studio, "OpenAI", lambda api_key=None: _FakeOpenAIImageClient(_tiny_png_bytes()))
    monkeypatch.delenv("AZURE_SPEECH_KEY", raising=False)
    monkeypatch.delenv("AZURE_SPEECH_REGION", raising=False)

    with pytest.raises(RuntimeError):
        content_studio.generate_video("raising a child", conn, text_api_key="fake", image_api_key="fake")


def test_generate_video_assembles_a_real_playable_mp4(monkeypatch, tmp_path):
    """End-to-end through the real ffmpeg assembly step (only the model/
    image-API/Azure calls are mocked, same "mock the billed calls, run the
    real local tool for real" split the rest of this repo uses for
    Tesseract/PyMuPDF) - confirms the actual video file is valid, not just
    that a path string was returned."""
    conn = _tmp_conn(tmp_path)
    _insert(conn, "parenting.md", "Tips on how to raise a child with patience.")

    monkeypatch.setattr(
        content_studio.book_compiler, "compile_book",
        lambda *a, **k: {"markdown": "A short narration script.", "sources": ["parenting.md (page 1/1)"]},
    )
    monkeypatch.setattr(content_studio, "OpenAI", lambda api_key=None: _FakeOpenAIImageClient(_tiny_png_bytes()))
    monkeypatch.setattr(
        content_studio.tts, "synthesize",
        lambda text, region=None, api_key=None: _tiny_mp3_bytes(),
    )

    result = content_studio.generate_video(
        "raising a child", conn, text_api_key="fake", image_api_key="fake",
        azure_speech_key="fake", azure_speech_region="eastus",
    )

    assert result["script"] == "A short narration script."
    assert result["sources"] == ["parenting.md (page 1/1)"]
    assert result["video_url"].startswith(content_studio.VIDEOS_URL_PREFIX + "/")

    import os
    video_path = os.path.join(content_studio.VIDEOS_DIR, os.path.basename(result["video_url"]))
    assert os.path.exists(video_path)
    assert os.path.getsize(video_path) > 0

    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "stream=codec_type,width,height",
         "-of", "default=noprint_wrappers=1", video_path],
        capture_output=True, text=True,
    )
    assert probe.returncode == 0, probe.stderr
    assert "codec_type=video" in probe.stdout
    assert "codec_type=audio" in probe.stdout
    assert f"width={content_studio._VIDEO_WIDTH}" in probe.stdout
    assert f"height={content_studio._VIDEO_HEIGHT}" in probe.stdout


def test_assemble_video_raises_a_clear_error_when_ffmpeg_is_missing(monkeypatch, tmp_path):
    def _fake_run(*args, **kwargs):
        raise FileNotFoundError("no such file: ffmpeg")

    monkeypatch.setattr(content_studio.subprocess, "run", _fake_run)
    with pytest.raises(RuntimeError, match="ffmpeg"):
        content_studio._assemble_video(str(tmp_path / "in.png"), str(tmp_path / "in.mp3"), str(tmp_path / "out.mp4"))
